apiVersion: apps/v1
kind: Deployment
metadata:
  name: udmis-pods
spec:
  selector:
    matchLabels:
      app: udmis
      role: master
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: udmis
        role: master
        tier: backend
    spec:
      containers:
      - name: udmis-core
        image: @IMAGE@
        imagePullPolicy: Always
        env:
        - name: GCP_PROJECT
          value: @PROJECT@
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: secret-volume
          mountPath: /udmi
          readOnly: true
      volumes:
        - name: secret-volume
          projected:
            sources:
            - secret:
                name: clearblade.json
                optional: true
