apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubber-pool
spec:
  selector:
    matchLabels:
      app: pubber
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pubber
    spec:
      containers:
      - name: pubber
        image: "us.gcr.io/${GCP_PROJECT}/pubber:latest"
        imagePullPolicy: Always
        env:
          - name: PUBBER_INSTANCES
            value: "40"
        resources:
          requests:
            memory: 300Mi
            cpu: 10m
